#!/usr/bin/env python3

ones_with_codes = [ 8, 10, 11, 12, 13, 14, 17 ]

print("/* AUTOGENERATED, DO NOT MODIFY */")
print("/* And in source control, too, because I'm a fuck. */")
print(".align 16")
print(".global entry_stubs")
print("entry_stubs:")
for i in range(256):
    print(".align 16")
    if not i in ones_with_codes:
        print("    pushl $0")
    print("    pushl $%d" % i)
    print("    jmp common_entry_asm")
